apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations: 
    kubernetes.io/ingress.class: nginx
spec: 
  rules: 
    - host: post.com
      http:
        paths:
          - path: /posts/allPosts
            pathType: Prefix
            backend:
              service:
                name: query-cluster-service
                port:
                  number: 8002
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: post-cluster-service
                port:
                  number: 8000
          - path: /comments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: comment-cluster-service
                port:
                  number: 8001
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: react-client-cluster-service
                port:
                  number: 3000